/* Autogenerated file. Do not edit manually. */

import { defineComponent, Type as RecsType, World } from "@latticexyz/recs";

export function defineContractComponents(world: World) {
  return {
    Player: (() => {
      const name = "Player";
      return defineComponent(
        world,
        {
          exp: RecsType.Number,
          gold: RecsType.Number,
          pos_1: RecsType.Number,
          pos_2: RecsType.Number,
          pos_3: RecsType.Number,
          pos_4: RecsType.Number,
          pos_5: RecsType.Number,
        },
        {
          metadata: {
            name: name,
            types: ["u32","u32","Hero","Hero","Hero","Hero","Hero"],
          },
        }
      );
    })(),
    CurrentDungeon: (() => {
      const name = "CurrentDungeon";
      return defineComponent(
        world,
        {
          dungeon_type: RecsType.Number,
          current_room: RecsType.Number,
          squad_health: RecsType.Number,
        },
        {
          metadata: {
            name: name,
            types: ["DungeonType","u8","u32"],
          },
        }
      );
    })(),
  };
}
