/* Autogenerated file. Do not edit manually. */

import { defineComponent, Type as RecsType, World } from "@latticexyz/recs";

export function defineContractComponents(world: World) {
  return {
    Player: (() => {
      const name = "Player";
      return defineComponent(
        world,
        {
          exp: RecsType.Number,
          gold: RecsType.Number,
        },
        {
          metadata: {
            name: name,
            types: ["u32","u32"],
          },
        }
      );
    })(),
    Hero1: (() => {
      const name = "Hero1";
      return defineComponent(
        world,
        {
          hero_type: RecsType.Number,
          exp: RecsType.Number,
        },
        {
          metadata: {
            name: name,
            types: ["HeroType","u32"],
          },
        }
      );
    })(),
    Hero2: (() => {
      const name = "Hero2";
      return defineComponent(
        world,
        {
          hero_type: RecsType.Number,
          exp: RecsType.Number,
        },
        {
          metadata: {
            name: name,
            types: ["HeroType","u32"],
          },
        }
      );
    })(),
    Hero3: (() => {
      const name = "Hero3";
      return defineComponent(
        world,
        {
          hero_type: RecsType.Number,
          exp: RecsType.Number,
        },
        {
          metadata: {
            name: name,
            types: ["HeroType","u32"],
          },
        }
      );
    })(),
    CurrentDungeon: (() => {
      const name = "CurrentDungeon";
      return defineComponent(
        world,
        {
          dungeon_type: RecsType.Number,
          current_room: RecsType.Number,
          squad_health: RecsType.Number,
        },
        {
          metadata: {
            name: name,
            types: ["DungeonType","u8","u32"],
          },
        }
      );
    })(),
  };
}
